#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
cd $SCRIPTPATH

if [ ! $TANGO_HOST ]; then 
    if [ -f /etc/tangorc ]; then
        . /etc/tangorc
    elif
        [ -f .tangorc ]; then
        . .tangorc
    fi
fi

#---------------------------------------------------------
#       Set the Class Path for Tango, ATK and AtkMoni usage
#---------------------------------------------------------
LIB_DIR=./libs;		export LIB_DIR
APP_DIR=./libs;	   	export APP_DIR


TANGO=$LIB_DIR/JTango.jar
TANGOATK=$LIB_DIR/ATKCore.jar:$LIB_DIR/ATKWidget.jar

APPLI_PACKAGE=fr.esrf.tangoatk.widget.attribute;	export APPLI_PACKAGE
APPLI_MAIN_CLASS=Trend; export APPLI_MAIN_CLASS

CLASSPATH=$TANGO:$TACO:$TANGOATK
export CLASSPATH
echo "CLASSPATH=$CLASSPATH"

#---------------------------------------------------------
#       Start the atkmoni process
#---------------------------------------------------------
#

/usr/bin/java -DTANGO_HOST=$TANGO_HOST $APPLI_PACKAGE.$APPLI_MAIN_CLASS $*

