#!/bin/bash

JAVA_BIN=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

#---------------------------------------------------------
#      Checking java version 
#---------------------------------------------------------
JAVA_VERSIONS_ACCEPTED=6,8
source check-java-version.sh

#---------------------------------------------------------
#       Open TANGO settings if any
#---------------------------------------------------------

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
cd $SCRIPTPATH

if [ ! $TANGO_HOST ]; then 
    if
        [ -f .tangorc ]; then
        . .tangorc
    elif [ -f /etc/tangorc ]; then
        . /etc/tangorc
    fi
fi

export TANGO_HOST

#---------------------------------------------------------
#       Set the Class Path for Tango, ATK and AtkMoni usage
#---------------------------------------------------------
LIB_DIR=./libs;		export LIB_DIR
APP_DIR=./libs;	   	export APP_DIR


TANGO=$LIB_DIR/JTango.jar
TANGOATK=$LIB_DIR/ATKCore.jar:$LIB_DIR/ATKWidget.jar

APPLI_PACKAGE=fr.esrf.tangoatk.widget.attribute;	export APPLI_PACKAGE
APPLI_MAIN_CLASS=Trend; export APPLI_MAIN_CLASS

CLASSPATH=$TANGO:$TACO:$TANGOATK
export CLASSPATH
echo "CLASSPATH=$CLASSPATH"



#---------------------------------------------------------
#       Start the atkmoni process
#---------------------------------------------------------
#

$JAVA_BIN -DTANGO_HOST=$TANGO_HOST $APPLI_PACKAGE.$APPLI_MAIN_CLASS $*

