#!/bin/bash
JAVA_VERSION_NEEDED=1.8

#---------------------------------------------------------
#      Checking java version 
#---------------------------------------------------------

JAVA_VERSION=`java -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f-2`
if [ "$JAVA_VERSION" != "$JAVA_VERSION_NEEDED" ]; then
        echo "Using java version $JAVA_VERSION instead of $JAVA_VERSION_NEEDED. Might not work"
else
        echo "Using java version $JAVA_VERSION. Should work"
fi

#---------------------------------------------------------
#       Open TANGO settings if any
#---------------------------------------------------------

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
cd $SCRIPTPATH

if [ ! $TANGO_HOST ]; then 
    if
        [ -f .tangorc ]; then
        . .tangorc
    elif [ -f /etc/tangorc ]; then
        . /etc/tangorc
    fi
fi

export TANGO_HOST

#---------------------------------------------------------
#       Set the Class Path for Tango, ATK and AtkMoni usage
#---------------------------------------------------------
LIB_DIR=./libs;		export LIB_DIR
APP_DIR=./libs;	   	export APP_DIR


TANGO=$LIB_DIR/JTango.jar
TANGOATK=$LIB_DIR/ATKCore.jar:$LIB_DIR/ATKWidget.jar

APPLI_PACKAGE=fr.esrf.tangoatk.widget.attribute;	export APPLI_PACKAGE
APPLI_MAIN_CLASS=Trend; export APPLI_MAIN_CLASS

CLASSPATH=$TANGO:$TACO:$TANGOATK
export CLASSPATH
echo "CLASSPATH=$CLASSPATH"



#---------------------------------------------------------
#       Start the atkmoni process
#---------------------------------------------------------
#

/usr/bin/java -DTANGO_HOST=$TANGO_HOST $APPLI_PACKAGE.$APPLI_MAIN_CLASS $*

