#!/bin/bash
#

JAVA_VERSION_NEEDED=1.8

#---------------------------------------------------------
#      Checking java version 
#---------------------------------------------------------

JAVA_VERSIONS_ACCEPTED=6,8
source check-java-version.sh

#---------------------------------------------------------
#       Open TANGO settings if any
#---------------------------------------------------------
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
cd $SCRIPTPATH


if [ ! $TANGO_HOST ]; then 
    if
        [ -f .tangorc ]; then
        . .tangorc
    elif [ -f /etc/tangorc ]; then
        . /etc/tangorc
    fi
fi

export TANGO_HOST

#---------------------------------------------------------
#       Set the Class Path for Tango and AtkPanel usage
#---------------------------------------------------------
LIB_DIR=./libs;   export LIB_DIR


TANGO=$LIB_DIR/TangORB.jar
TANGOATK=$LIB_DIR/ATKCore.jar:$LIB_DIR/ATKWidget.jar
ATKPANEL=$LIB_DIR/ATKPanel.jar

CLASSPATH=$ATKPANEL:$TANGOATK:$TANGO
export CLASSPATH

LIBPATH=./libs
export LIBPATH

#---------------------------------------------------------
#	Start the atkpanel process
#---------------------------------------------------------

$JAVA_BIN -mx128m -Djava.library.path=$LIBPATH -DTANGO_HOST=$TANGO_HOST atkpanel.MainPanel $*
