#!/bin/bash
#

JAVA_VERSION_NEEDED=1.8
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
cd $SCRIPTPATH


if [ ! $TANGO_HOST ]; then 
    if
        [ -f .tangorc ]; then
        . .tangorc
    elif [ -f /etc/tangorc ]; then
        . /etc/tangorc
    fi
fi

export TANGO_HOST

#---------------------------------------------------------
#       Set the Class Path for Tango and AtkPanel usage
#---------------------------------------------------------
LIB_DIR=./libs;   export LIB_DIR


TANGO=$LIB_DIR/TangORB.jar
TANGOATK=$LIB_DIR/ATKCore.jar:$LIB_DIR/ATKWidget.jar
ATKPANEL=$LIB_DIR/ATKPanel.jar

CLASSPATH=$ATKPANEL:$TANGOATK:$TANGO
export CLASSPATH

LIBPATH=./libs
export LIBPATH

#---------------------------------------------------------
#	Check java version
#---------------------------------------------------------

JAVA_VERSION=`java -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f-2`
if [ "$JAVA_VERSION" != "$JAVA_VERSION_NEEDED" ]; then
        echo "Using java version $JAVA_VERSION instead of $JAVA_VERSION_NEEDED. Might not work"
else
        echo "Using java version $JAVA_VERSION. Should work"
fi

#---------------------------------------------------------
#	Start the atkpanel process
#---------------------------------------------------------

/usr/bin/java -mx128m -Djava.library.path=$LIBPATH -DTANGO_HOST=$TANGO_HOST atkpanel.MainPanel $*
