#!/bin/bash
#
TANGO_HOME=/usr/local;		export TANGO_HOME

if [ ! $TANGO_HOST ] && [ -f /etc/tangorc ]; then
   . /etc/tangorc
fi

#---------------------------------------------------------
#       Set the Class Path for Tango and AtkPanel usage
#---------------------------------------------------------
LIB_DIR=./libs;   export LIB_DIR


TANGO=$LIB_DIR/TangORB.jar
TANGOATK=$LIB_DIR/ATKCore.jar:$LIB_DIR/ATKWidget.jar
ATKPANEL=$LIB_DIR/atkpanel.jar

CLASSPATH=$ATKPANEL:$TANGOATK:$TANGO
export CLASSPATH

LIBPATH=./libs
export LIBPATH

#---------------------------------------------------------
#	Start the atkpanel process
#---------------------------------------------------------

/usr/bin/java -mx128m -Djava.library.path=$LIBPATH -DTANGO_HOST=$TANGO_HOST atkpanel.MainPanel $*
