#!/bin/bash

JAVA_VERSION_NEEDED=1.8

#---------------------------------------------------------
#      Checking java version 
#---------------------------------------------------------

JAVA_VERSION=`java -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f-2`
if [ "$JAVA_VERSION" != "$JAVA_VERSION_NEEDED" ]; then
        echo "Using java version $JAVA_VERSION instead of $JAVA_VERSION_NEEDED. Might not work"
else
        echo "Using java version $JAVA_VERSION. Should work"
fi

#---------------------------------------------------------
#       Open TANGO settings if any
#---------------------------------------------------------
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
cd $SCRIPTPATH

#---------------------------------------------------------
#
#---------------------------------------------------------

if [ ! $TANGO_HOST ]; then 
    if
        [ -f .tangorc ]; then
        . .tangorc
    elif [ -f /etc/tangorc ]; then
        . /etc/tangorc
    fi
fi

export TANGO_HOST

LIB_DIR=./libs;	    export LIB_DIR
APP_DIR=./libs;	    export APP_DIR

#---------------------------------------------------------
#       Set the Class Path Jdraw usage
#---------------------------------------------------------


TANGO=$LIB_DIR/TangORB.jar
TANGOATK=$LIB_DIR/ATKCore.jar:$LIB_DIR/ATKWidget.jar:$LIB_DIR/ATKPanel.jar

APPLI_PACKAGE=fr.esrf.tangoatk.widget.util.jdraw;	export APPLI_PACKAGE
APPLI_MAIN_CLASS=JDrawEditorFrame; export APPLI_MAIN_CLASS

CLASSPATH=$TANGOATK:$TANGO
export CLASSPATH
echo "CLASSPATH=$CLASSPATH"

LIBPATH=$SCRIPTPATH/libjdraw
export LIBPATH

echo Running Jdraw ...

#---------------------------------------------------------
#       Start the Jdraw process
#---------------------------------------------------------
#

/usr/bin/java -Djava.library.path=$LIBPATH $APPLI_PACKAGE.$APPLI_MAIN_CLASS $@
