#!/bin/bash
#---------------------------------------------------------
#
#---------------------------------------------------------

export TANGO_HOST=172.25.65.1:10000

if [ ! $TANGO_HOST ] && [ -f /etc/tangorc ]; then
   . /etc/tangorc
fi

LIB_DIR=./;	    export LIB_DIR
APP_DIR=./;	    export APP_DIR
LIBPATH=./libjdraw/;	    export LIBPATH

#--------------------------------------------------------------------------
#       Set the Class Path for Tango, ATK and Simple Synoptic Appli in ATK
#--------------------------------------------------------------------------


TANGO=$LIB_DIR/TangORB.jar

TANGOATK=$LIB_DIR/ATKCore.jar:$LIB_DIR/ATKWidget.jar
ATKPANEL=$APP_DIR/atkpanel.jar


APPLI_PACKAGE=fr.esrf.tangoatk.widget.util.jdraw;	export APPLI_PACKAGE
APPLI_MAIN_CLASS=JDrawEditorFrame; export APPLI_MAIN_CLASS

CLASSPATH=$TACO:$TANGO:$TANGOATK:$ATKPANEL
export CLASSPATH
echo "CLASSPATH=$CLASSPATH"
echo "LIBPATH=$LIBPATH"

echo Running Jdraw ...

#---------------------------------------------------------
#       Start the Jdraw process
#---------------------------------------------------------
#

/usr/bin/java -DLIBPATH=$LIBPATH $APPLI_PACKAGE.$APPLI_MAIN_CLASS $@

