#!/bin/bash


SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
cd $SCRIPTPATH

#---------------------------------------------------------
#
#---------------------------------------------------------

LIB_DIR=./libs;	    export LIB_DIR
APP_DIR=./libs;	    export APP_DIR

#---------------------------------------------------------
#       Set the Class Path Jdraw usage
#---------------------------------------------------------


TANGO=$LIB_DIR/TangORB.jar
TANGOATK=$LIB_DIR/ATKCore.jar:$LIB_DIR/ATKWidget.jar:$LIB_DIR/atkpanel.jar

APPLI_PACKAGE=fr.esrf.tangoatk.widget.util.jdraw;	export APPLI_PACKAGE
APPLI_MAIN_CLASS=JDrawEditorFrame; export APPLI_MAIN_CLASS

CLASSPATH=$TANGOATK:$TANGO
export CLASSPATH
echo "CLASSPATH=$CLASSPATH"

LIBPATH=./libs
export LIBPATH

echo Running Jdraw ...

#---------------------------------------------------------
#       Start the Jdraw process
#---------------------------------------------------------
#

/usr/bin/java -Djava.library.path=$LIBPATH $APPLI_PACKAGE.$APPLI_MAIN_CLASS $@
