#!/bin/bash

JAVA_VERSION_NEEDED=1.8

#---------------------------------------------------------
#      Checking java version 
#---------------------------------------------------------

JAVA_VERSION=`java -version 2>&1 | head -n 1 | cut -d'"' -f2 | cut -d'.' -f-2`
if [ "$JAVA_VERSION" != "$JAVA_VERSION_NEEDED" ]; then
        echo "Using java version $JAVA_VERSION instead of $JAVA_VERSION_NEEDED. Might not work"
else
        echo "Using java version $JAVA_VERSION. Should work"
fi

#---------------------------------------------------------
#       Open TANGO settings if any
#---------------------------------------------------------
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
cd $SCRIPTPATH


applet_name=jive3.MainPanel

if [ ! $TANGO_HOST ]; then 
    if
        [ -f .tangorc ]; then
        . .tangorc
    elif [ -f /etc/tangorc ]; then
        . /etc/tangorc
    fi
fi

#
# Define the CLASSPATH
#
JAVALIB=./libs
JAVABIN=./libs

ATK=$JAVALIB/ATKCore.jar:$JAVALIB/ATKWidget.jar:$JAVABIN/ATKPanel.jar
LOGVIEWER=$JAVALIB/LogViewer.jar
ASTOR=$JAVALIB/Astor.jar:$JAVALIB/tools_panel.jar
LOG4J=$JAVALIB/log4j.jar

CLASSPATH=$JAVALIB/TangORB.jar:$JAVABIN/Jive.jar:$ATK:$LOGVIEWER:$LOG4J:$ASTOR:.
export CLASSPATH

LIBPATH=./libs
export LIBPATH

/usr/bin/java \
    -mx128m \
    -Djava.library.path=$LIBPATH \
    -DTANGO_HOST=$TANGO_HOST \
     $applet_name $@
