#!/bin/bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
cd $SCRIPTPATH


applet_name=jive3.MainPanel

if [ ! $TANGO_HOST ]; then 
    if [ -f /etc/tangorc ]; then
        . /etc/tangorc
    elif
        [ -f .tangorc ]; then
        . .tangorc
    fi
fi

#
# Define the CLASSPATH
#
JAVALIB=./libs
JAVABIN=./libs

ATK=$JAVALIB/ATKCore.jar:$JAVALIB/ATKWidget.jar:$JAVABIN/ATKpanel.jar
LOGVIEWER=$JAVALIB/LogViewer.jar
ASTOR=$JAVALIB/Astor.jar:$JAVALIB/tools_panel.jar
LOG4J=$JAVALIB/log4j.jar

CLASSPATH=$JAVALIB/TangORB.jar:$JAVABIN/Jive.jar:$ATK:$LOGVIEWER:$LOG4J:$ASTOR:.
export CLASSPATH

LIBPATH=./libs
export LIBPATH

/usr/bin/java \
    -mx128m \
    -Djava.library.path=$LIBPATH \
    -DTANGO_HOST=$TANGO_HOST \
     $applet_name $@
